[package]
name = "crux-integration-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
tempfile = { workspace = true }
ureq = { workspace = true, features = ["json"] }
serde_json = { workspace = true }
portpicker = "0.1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace = true }
tokio-stream = { workspace = true }
prost = { workspace = true }
corecrux-proto = { path = "../corecrux-proto" }

[lints]
workspace = true
