// Copyright (c) 2026 CueCrux Ltd.
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root.

//! The published `pack.conformance.v1` schema document — the MIT-licensed
//! artefact third parties implement against — and the checks that keep it
//! honest.
//!
//! Three separate claims are tested here, because they fail independently:
//!
//! 1. **The committed document is what the code says the format is.** It is
//!    generated by `conformance::json_schema`, so a field added to the Rust
//!    types without regenerating fails here rather than silently shipping a
//!    schema that rejects manifests the daemon accepts.
//! 2. **The document is a usable JSON Schema.** Validated structurally, and
//!    then used as a real oracle by [`validate_against_schema`] below, which
//!    implements the keyword subset the document actually uses.
//! 3. **It is MIT.** The whole point of publishing a format is that someone
//!    else can implement it; an Apache-2.0-only schema does not get
//!    implemented by an MIT registry.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use crux_integrations::conformance::{self, SCHEMA_DOCUMENT_ID, SCHEMA_DOCUMENT_PATH};
use serde_json::Value;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn schema_document_path() -> PathBuf {
    repo_root().join(SCHEMA_DOCUMENT_PATH)
}

/// Exactly what the committed file must contain: pretty JSON plus the
/// trailing newline every text file in the tree ends with.
fn rendered_schema_document() -> String {
    let mut rendered = serde_json::to_string_pretty(&conformance::json_schema()).expect("render schema document");
    rendered.push('\n');
    rendered
}

#[test]
fn published_schema_document_matches_the_generator() {
    let path = schema_document_path();
    let committed = fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "{} is missing ({err}); regenerate it with:\n  cargo test -p crux-integrations --test pack_conformance_schema -- --ignored regen_pack_conformance_schema_document",
            path.display()
        )
    });
    assert_eq!(
        committed,
        rendered_schema_document(),
        "{} has drifted from conformance::json_schema; regenerate it with:\n  cargo test -p crux-integrations --test pack_conformance_schema -- --ignored regen_pack_conformance_schema_document",
        path.display()
    );
}

#[test]
fn published_schema_document_is_a_well_formed_json_schema() {
    let schema = conformance::json_schema();
    assert_eq!(
        schema["$schema"], "https://json-schema.org/draft/2020-12/schema",
        "the dialect must be declared, or a validator has to guess"
    );
    assert_eq!(schema["$id"], SCHEMA_DOCUMENT_ID);
    assert_eq!(schema["title"], conformance::PACK_CONFORMANCE_SCHEMA_V1);

    // Every `$ref` in the document must resolve inside `$defs`. A dangling
    // ref is the failure a hand-edited schema produces, and it turns every
    // downstream validator into a silent pass or a hard error depending on
    // the implementation.
    let defs: BTreeSet<String> = schema["$defs"]
        .as_object()
        .expect("$defs must be an object")
        .keys()
        .cloned()
        .collect();
    let mut refs = BTreeSet::new();
    collect_refs(&schema, &mut refs);
    assert!(!refs.is_empty(), "a schema with no $refs has not been factored at all");
    for reference in &refs {
        let name = reference
            .strip_prefix("#/$defs/")
            .unwrap_or_else(|| panic!("unexpected $ref form '{reference}'"));
        assert!(defs.contains(name), "$ref '{reference}' does not resolve in $defs");
    }
    // And nothing unreachable: a definition no ref points at is dead weight
    // an implementer has to read and then discover is unused.
    for name in &defs {
        assert!(
            refs.contains(&format!("#/$defs/{name}")),
            "$defs/{name} is unreachable from the root schema"
        );
    }
}

#[test]
fn published_schema_document_carries_the_mit_notice() {
    let schema = conformance::json_schema();
    let comment = schema["$comment"].as_str().unwrap_or_default();
    assert!(
        comment.contains("SPDX-License-Identifier: MIT"),
        "the schema file must carry its own SPDX licence identifier: a vendored copy travels without the repo"
    );
    assert_eq!(schema["license"]["spdx"], "MIT");

    let spec = fs::read_to_string(repo_root().join("docs/spec/pack-conformance-v1.md")).expect("read the spec doc");
    assert!(
        spec.contains("MIT License") && spec.contains("WITHOUT WARRANTY OF ANY KIND"),
        "docs/spec/pack-conformance-v1.md must reproduce the full MIT notice the schema points at"
    );
    assert!(
        spec.contains(SCHEMA_DOCUMENT_PATH),
        "the spec doc must reference the schema file by path"
    );
}

#[test]
fn schema_accepts_a_valid_conformance_block() {
    let block = serde_json::to_value(sample_declaration()).expect("encode declaration");
    let errors = validate_against_schema(&conformance::json_schema(), &block);
    assert!(errors.is_empty(), "valid block rejected by the schema: {errors:?}");
}

#[test]
fn schema_accepts_the_reference_packs_conformance_block() {
    // The published schema and the committed reference pack are the two
    // halves an implementer gets. If they disagree, whichever one they picked
    // up first is wrong, and there is no way to tell which.
    let manifest_path = repo_root().join("integrations/community/ext.conformance.reference/0.2.0/manifest.json");
    let manifest: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path).unwrap_or_else(|err| panic!("read {}: {err}", manifest_path.display())),
    )
    .expect("parse reference manifest");
    let block = manifest
        .get("conformance")
        .expect("the reference pack must ship a conformance block");
    let errors = validate_against_schema(&conformance::json_schema(), block);
    assert!(
        errors.is_empty(),
        "the reference pack's block does not validate against the published schema: {errors:?}"
    );
}

#[test]
fn schema_rejects_a_block_that_the_rust_validator_also_rejects() {
    let schema = conformance::json_schema();

    // Missing a required field.
    let mut block = serde_json::to_value(sample_declaration()).expect("encode");
    if let Some(object) = block.as_object_mut() {
        object.remove("envelope");
    }
    assert!(
        !validate_against_schema(&schema, &block).is_empty(),
        "a block missing `envelope` must be rejected"
    );

    // An enum value outside the closed set.
    let mut block = serde_json::to_value(sample_declaration()).expect("encode");
    block["invariants"][0]["kind"] = Value::String("do_no_harm".to_string());
    assert!(
        !validate_against_schema(&schema, &block).is_empty(),
        "an invariant kind no harness can evaluate must be rejected"
    );

    // A float bound. The block is signed and JSON has no canonical float, so
    // a fractional bound is not a tighter promise, it is an unverifiable one.
    let mut block = serde_json::to_value(sample_declaration()).expect("encode");
    block["envelope"]["max_tokens_per_call"] = serde_json::json!(511.5);
    assert!(
        !validate_against_schema(&schema, &block).is_empty(),
        "a fractional envelope bound must be rejected"
    );

    // An unknown field: `additionalProperties: false` everywhere means a
    // typo'd bound is a rejection, not a silently ignored promise.
    let mut block = serde_json::to_value(sample_declaration()).expect("encode");
    block["envelope"]["max_toknes_per_call"] = serde_json::json!(4096);
    assert!(
        !validate_against_schema(&schema, &block).is_empty(),
        "an unknown envelope field must be rejected rather than ignored"
    );
}

#[test]
#[ignore = "writer: run with -- --ignored regen_pack_conformance_schema_document to regenerate the published schema"]
fn regen_pack_conformance_schema_document() {
    let path = schema_document_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create docs/spec");
    }
    fs::write(&path, rendered_schema_document()).expect("write schema document");
}

// ── A JSON Schema validator for the keywords this document uses ──────────
//
// Not a general-purpose implementation and not trying to be. The alternative
// was a third-party validator crate, which would put a regex engine and a
// dozen transitive dependencies into the build to check one committed file.
// The keywords below are exactly the ones `conformance::json_schema` emits,
// and `published_schema_document_uses_only_supported_keywords` fails if that
// stops being true — so the subset can never quietly fall behind the schema
// it is supposed to check.
//
// `pattern` is the one deliberate omission (it needs a regex engine); the
// two patterned fields, `sha256` and `min_daemon_version`, are enforced by
// `PackConformance::validate` instead, and that is asserted by the unit tests
// in the conformance module.

const SUPPORTED_KEYWORDS: &[&str] = &[
    "$schema",
    "$id",
    "$defs",
    "$ref",
    "$comment",
    "title",
    "description",
    "license",
    "type",
    "properties",
    "required",
    "additionalProperties",
    "items",
    "enum",
    "const",
    "minimum",
    "maximum",
    "minItems",
    "maxItems",
    "minLength",
    "pattern",
];

#[test]
fn published_schema_document_uses_only_supported_keywords() {
    let mut unsupported = BTreeSet::new();
    collect_keywords(&conformance::json_schema(), true, &mut unsupported);
    assert!(
        unsupported.is_empty(),
        "the schema uses keywords this test's validator does not implement: {unsupported:?} — \
         either implement them in validate_against_schema or stop emitting them"
    );
}

fn collect_keywords(node: &Value, is_schema: bool, out: &mut BTreeSet<String>) {
    let Some(object) = node.as_object() else {
        return;
    };
    for (key, value) in object {
        if is_schema && !SUPPORTED_KEYWORDS.contains(&key.as_str()) {
            out.insert(key.clone());
        }
        match key.as_str() {
            // Children of these keywords are schemas keyed by name.
            "$defs" | "properties" => {
                if let Some(children) = value.as_object() {
                    for child in children.values() {
                        collect_keywords(child, true, out);
                    }
                }
            }
            // Children of these keywords are schemas directly.
            "items" => collect_keywords(value, true, out),
            // Everything else is data, not a schema.
            _ => {}
        }
    }
}

fn collect_refs(node: &Value, out: &mut BTreeSet<String>) {
    match node {
        Value::Object(map) => {
            for (key, value) in map {
                if key == "$ref" {
                    if let Some(reference) = value.as_str() {
                        out.insert(reference.to_string());
                    }
                } else {
                    collect_refs(value, out);
                }
            }
        }
        Value::Array(items) => items.iter().for_each(|item| collect_refs(item, out)),
        _ => {}
    }
}

/// Validate `instance` against `schema`, returning one message per violation.
fn validate_against_schema(schema: &Value, instance: &Value) -> Vec<String> {
    let mut errors = Vec::new();
    check(schema, schema, instance, "$", &mut errors);
    errors
}

fn check(root: &Value, schema: &Value, instance: &Value, path: &str, errors: &mut Vec<String>) {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let Some(name) = reference.strip_prefix("#/$defs/") else {
            errors.push(format!("{path}: unresolvable $ref '{reference}'"));
            return;
        };
        match root.get("$defs").and_then(|defs| defs.get(name)) {
            Some(resolved) => check(root, resolved, instance, path, errors),
            None => errors.push(format!("{path}: $ref '{reference}' not found")),
        }
        return;
    }

    if let Some(expected) = schema.get("const") {
        if instance != expected {
            errors.push(format!("{path}: expected const {expected}, got {instance}"));
        }
    }
    if let Some(Value::Array(allowed)) = schema.get("enum") {
        if !allowed.contains(instance) {
            errors.push(format!("{path}: {instance} is not one of {allowed:?}"));
        }
    }

    match schema.get("type").and_then(Value::as_str) {
        Some("object") => check_object(root, schema, instance, path, errors),
        Some("array") => check_array(root, schema, instance, path, errors),
        Some("string") => check_string(schema, instance, path, errors),
        Some("integer") => check_integer(schema, instance, path, errors),
        Some("boolean") => {
            if !instance.is_boolean() {
                errors.push(format!("{path}: expected boolean, got {instance}"));
            }
        }
        Some(other) => errors.push(format!("{path}: unsupported type '{other}' in schema")),
        // No `type`: any JSON value is allowed (the `args` field).
        None => {}
    }
}

fn check_object(root: &Value, schema: &Value, instance: &Value, path: &str, errors: &mut Vec<String>) {
    let Some(object) = instance.as_object() else {
        errors.push(format!("{path}: expected object, got {instance}"));
        return;
    };
    let properties = schema.get("properties").and_then(Value::as_object);
    if let Some(Value::Array(required)) = schema.get("required") {
        for field in required {
            if let Some(name) = field.as_str() {
                if !object.contains_key(name) {
                    errors.push(format!("{path}: missing required property '{name}'"));
                }
            }
        }
    }
    let additional_allowed = schema.get("additionalProperties").and_then(Value::as_bool) != Some(false);
    for (name, value) in object {
        match properties.and_then(|properties| properties.get(name)) {
            Some(child) => check(root, child, value, &format!("{path}.{name}"), errors),
            None if !additional_allowed => {
                errors.push(format!("{path}: unexpected property '{name}'"));
            }
            None => {}
        }
    }
}

fn check_array(root: &Value, schema: &Value, instance: &Value, path: &str, errors: &mut Vec<String>) {
    let Some(items) = instance.as_array() else {
        errors.push(format!("{path}: expected array, got {instance}"));
        return;
    };
    if let Some(minimum) = schema.get("minItems").and_then(Value::as_u64) {
        if (items.len() as u64) < minimum {
            errors.push(format!(
                "{path}: expected at least {minimum} items, got {}",
                items.len()
            ));
        }
    }
    if let Some(maximum) = schema.get("maxItems").and_then(Value::as_u64) {
        if (items.len() as u64) > maximum {
            errors.push(format!("{path}: expected at most {maximum} items, got {}", items.len()));
        }
    }
    if let Some(item_schema) = schema.get("items") {
        for (index, item) in items.iter().enumerate() {
            check(root, item_schema, item, &format!("{path}[{index}]"), errors);
        }
    }
}

fn check_string(schema: &Value, instance: &Value, path: &str, errors: &mut Vec<String>) {
    let Some(text) = instance.as_str() else {
        errors.push(format!("{path}: expected string, got {instance}"));
        return;
    };
    if let Some(minimum) = schema.get("minLength").and_then(Value::as_u64) {
        if (text.chars().count() as u64) < minimum {
            errors.push(format!("{path}: expected at least {minimum} characters"));
        }
    }
}

fn check_integer(schema: &Value, instance: &Value, path: &str, errors: &mut Vec<String>) {
    let Some(number) = instance.as_u64() else {
        errors.push(format!("{path}: expected a non-negative integer, got {instance}"));
        return;
    };
    if let Some(minimum) = schema.get("minimum").and_then(Value::as_u64) {
        if number < minimum {
            errors.push(format!("{path}: {number} is below the minimum {minimum}"));
        }
    }
    if let Some(maximum) = schema.get("maximum").and_then(Value::as_u64) {
        if number > maximum {
            errors.push(format!("{path}: {number} is above the maximum {maximum}"));
        }
    }
}

/// A minimal valid declaration, kept independent of the reference pack so a
/// change to the committed pack cannot quietly weaken these schema tests.
fn sample_declaration() -> conformance::PackConformance {
    use conformance::{
        BehaviouralEnvelope, CompatibilityAssertions, DecayEnvelope, DeclaredCase, ExpectedMutations, InvariantKind,
        InvariantTest, PackConformance, ReplayCorpus, UndoEnvelope, PACK_CONFORMANCE_SCHEMA_V1,
    };

    PackConformance {
        schema: PACK_CONFORMANCE_SCHEMA_V1.to_string(),
        claimed_capabilities: vec!["facts:read".to_string()],
        expected_mutations: ExpectedMutations {
            facts: Vec::new(),
            receipts: Vec::new(),
        },
        replay_corpus: ReplayCorpus {
            corpus_id: "sample-v1".to_string(),
            path: "replay-corpus.json".to_string(),
            sha256: "0".repeat(64),
            cases: vec![DeclaredCase {
                case_id: "read-default".to_string(),
                tool_name: "ext.sample.read".to_string(),
                args: serde_json::json!({ "limit": 1 }),
            }],
        },
        invariants: vec![InvariantTest {
            id: "read-only".to_string(),
            description: "The pack writes nothing.".to_string(),
            kind: InvariantKind::NoUndeclaredFactWrites,
            applies_to_cases: Vec::new(),
        }],
        envelope: BehaviouralEnvelope {
            max_tokens_per_call: 512,
            max_tokens_per_run: 512,
            max_latency_ms_per_call: 1_000,
            max_latency_ms_per_run: 1_000,
            max_response_bytes_per_call: 8_192,
            max_fact_writes_per_call: 0,
            decay: DecayEnvelope {
                min_half_life_seconds: 0,
                max_refreshes_per_call: 0,
            },
            max_contradiction_rate_ppm: 0,
            undo: UndoEnvelope {
                max_operations_per_call: 0,
                max_latency_ms: 0,
            },
        },
        compatibility: CompatibilityAssertions {
            min_daemon_version: "0.5.0".to_string(),
            manifest_schema: crux_integrations::INTEGRATION_SCHEMA_V1.to_string(),
            supersedes: Vec::new(),
            migrations: Vec::new(),
            rollback_safe: true,
        },
    }
}
