#!/usr/bin/env bash
# Copyright (c) 2026 CueCrux Ltd. All rights reserved.
# Licensed under the CueCrux Community Licence (CCL v1.0).
#
# build-llms-full.sh — generate llms-full.txt from llms.txt.
#
# llms.txt is the curated index (llmstxt.org); llms-full.txt is its expansion — the full
# content of every local document llms.txt links, concatenated in link order with one
# separator per file, so an agent can ingest the whole public doc surface in one fetch.
# Deterministic by construction: no timestamps, content ordering follows llms.txt.
# Directory links (e.g. docs/adr/) expand to their *.md files, sorted.
#
# Usage:
#   bash scripts/build-llms-full.sh           # (re)write llms-full.txt
#   bash scripts/build-llms-full.sh --check   # exit 1 if llms-full.txt is stale
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INDEX="$ROOT/llms.txt"
OUT="$ROOT/llms-full.txt"

if [[ ! -f "$INDEX" ]]; then
  echo "FATAL: $INDEX not found" >&2
  exit 1
fi

emit() {
  printf '# ============================================================\n'
  printf '# BEGIN %s\n' "$1"
  printf '# ============================================================\n\n'
  cat "$ROOT/$1"
  printf '\n'
}

generate() {
  printf '# llms-full.txt — generated by scripts/build-llms-full.sh. Do not edit by hand.\n'
  printf '# Expansion of llms.txt: the full content of every linked local document.\n\n'
  emit "llms.txt"
  # Local link targets from llms.txt, in order, deduplicated.
  grep -oE '\]\([^)]+\)' "$INDEX" | sed 's/^](\(.*\))$/\1/' | awk '!seen[$0]++' \
    | while IFS= read -r target; do
      case "$target" in
        http://*|https://*|mailto:*) continue ;;
        llms-full.txt) continue ;;  # never expand the output into itself
      esac
      if [[ -d "$ROOT/${target%/}" ]]; then
        while IFS= read -r sub; do
          emit "${sub#"$ROOT"/}"
        done < <(find "$ROOT/${target%/}" -maxdepth 1 -name '*.md' | sort)
      elif [[ -f "$ROOT/$target" ]]; then
        emit "$target"
      else
        echo "FATAL: llms.txt links '$target' which does not exist" >&2
        exit 1
      fi
    done
}

if [[ "${1:-}" == "--check" ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "STALE: llms-full.txt missing — run scripts/build-llms-full.sh" >&2
    exit 1
  fi
  if ! diff -q <(generate) "$OUT" >/dev/null; then
    echo "STALE: llms-full.txt does not match llms.txt expansion — run scripts/build-llms-full.sh" >&2
    exit 1
  fi
  echo "OK: llms-full.txt is fresh."
  exit 0
fi

generate > "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"
